### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Scorchys12**
updated hak and tlk with world creatures - dantooine

### CODE REVIEW

**Comment by zunath** [comment]
The raw hak file shouldn't be committed. You want to commit the loose files. You've edited the .itp hak based on this PR, so remove that .hak file and instead check in the individual files you've changed. Also if you've edited the TLK please run ConvertTlk.cmd to update the JSON representation of the data.

**Review by zunath — CHANGES_REQUESTED** [review]
Requesting changes

**Review by Scorchys12 — COMMENTED** [review]
This should be it

**Review by zunath — CHANGES_REQUESTED** [review]
Please remove the swlor2_itp.hak file.

**Pull request closed without merging**
