### PR TITLE
Terallis hak changes

### PR DESCRIPTION
**Pull request by Terallis**
- Fixed textures on a couple tilesets
- Removed unused and useless tilesets
- Added new KotOR creature models
- Added new helmets
- Added new cloaks
- Added some custom player portraits
- Added Rodian race lines

### CODE REVIEW

**Comment by zunath** [comment]
I have a feeling you have an outdated copy of the repository. There are a ton of deletions in your PR and I'm very hesitant to merge it as-is. These are the guides I recommend for updating your fork.

One time configuration: https://help.github.com/en/articles/configuring-a-remote-for-a-fork

Updating your fork: https://help.github.com/en/articles/syncing-a-fork

**Comment by Terallis** [comment]
Isn't outdated. I looked over all of that. The deletions were of unused, useless tilesets as well as a metric ton of dds converted textures of an existing tileset that Symphony did.

**Comment by zunath** [comment]
You're definitely behind by 62 commits so please make sure you fix that. Here's a screenshot to show you how I know: https://i.imgur.com/fhhTyQH.png

If you need help getting your branch synced with master let me know on Discord.


Also as I was doing a spot check, I noticed the Rodian appearance points to Bothan (152) in appearances.2da, but this should actually be 164 as that's the ID it has in racialtypes.2da

**Comment by zunath** [comment]
No activity on this in a few months now. Closing it out. Feel free to reopen the PR if/when you update your fork.

**Pull request closed without merging**
